# Generated by Django 3.2.5 on 2021-11-10 06:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('module', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModuleCore',
            fields=[
                ('module_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='module.module')),
            ],
            options={
                'verbose_name': 'module core',
                'verbose_name_plural': 'module cores',
                'db_table': 'core_module_core',
                'ordering': ['-provider_type', 'name'],
                'abstract': False,
            },
            bases=('module.module',),
        ),
        migrations.CreateModel(
            name='ModuleGit',
            fields=[
                ('module_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='module.module')),
            ],
            options={
                'verbose_name': 'module git',
                'verbose_name_plural': 'module gits',
                'db_table': 'core_module_git',
                'ordering': ['-provider_type', 'name'],
                'abstract': False,
            },
            bases=('module.module',),
        ),
    ]
