# Generated by Django 3.2.5 on 2021-11-10 06:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupRole',
            fields=[
                ('group_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='group.group')),
            ],
            options={
                'verbose_name': 'group role',
                'verbose_name_plural': 'group roles',
                'db_table': 'core_group_role',
                'ordering': ['name'],
                'abstract': False,
            },
            bases=('group.group',),
        ),
    ]
